version: "3.8"

networks:
  proxy_bridge:
    external: true

services:
  portfolio:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: portfolio-container
    restart: always
    networks:
      proxy_bridge:
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.portfolio-secure.entrypoints: ${ENTRYPOINT}
      traefik.http.routers.portfolio-secure.rule: Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      traefik.http.services.portfolio-secure.loadbalancer.server.port: 80
      traefik.http.routers.portfolio-secure.middlewares: main-redirect@file
      traefik.docker.network: proxy_bridge
